### PR TITLE
Add Docker and Poetry support

### PR DESCRIPTION
**Pull request by fabiocarneiro**
I know this app is not maintained for ages, but I've been working on a similar solution and wanted to give it a try. It was really painful to install and find the right dependencies, but I was able to get it running with Poetry and Docker.

### CODE REVIEW

**Comment by tbarbugli** [comment]
@fabiocarneiro this PR is awesome 😃Thank you for pushing this!

I was planning to do something like this since forever but never got the time to do it. I am going to have a look at it and let you know. Just for my curiosity, for what kind of project do you use stream-framework?

**Comment by fabiocarneiro** [comment]
I'm actually not using it, and not even sure I will. I've been researching on the subject and it seemed it would be easy to just run this project and try. Unfortunately, it wasn't true, and since I spent a lot of time-fighting with Pipenv (which doesn`t install at all with those dependencies), and I managed to install with Poetry, I think it would be useful for others...

**Comment by fabiocarneiro** [comment]
@tbarbugli Any news regarding this? I'd like to exclude it from my mental list of things to track. 

Isn't the Travis output enough to prove its working? The only thing missing is the support for Cassandra, but I guess it's not working with either of those in the current approach, so its definitely not a regression.

**Comment by tbarbugli** [comment]
@fabiocarneiro PR is good, I just needed a bit of time to review and play with it myself ;)

**Pull request merged**
